bot:
  build: .
  container_name: tg_bot-container
  restart: always
  stop_signal: SIGINT

  env_file:
    - ".env"

  environment:
    - PYTHONUNBUFFERED=1
    - REDIS_URL=redis://redis:6379/0
    - SELENIUM_REMOTE_URL=http://selenium:4444

  depends_on:
    postgres:
      condition: service_healthy
    selenium:
      condition: service_healthy
    redis:
      condition: service_healthy

  networks:
    - tg_bot
